// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4fvT5vskQMeOZ31Fw55_6AmesX8cVzo',
    appId: '1:1094812966602:web:440ff872f779f3dc245e33',
    messagingSenderId: '1094812966602',
    projectId: 'expense--tracker-6487e',
    authDomain: 'expense--tracker-6487e.firebaseapp.com',
    storageBucket: 'expense--tracker-6487e.appspot.com',
    measurementId: 'G-ZM2TZVGZT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw7ySrACxGfVOzTdQv793WkVvTeZmsFcM',
    appId: '1:1094812966602:android:3b317b385d65b465245e33',
    messagingSenderId: '1094812966602',
    projectId: 'expense--tracker-6487e',
    storageBucket: 'expense--tracker-6487e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNyqDzBy_M3kq5QsV_B6hUT5FVna4FkKw',
    appId: '1:1094812966602:ios:91c3d709a07983a8245e33',
    messagingSenderId: '1094812966602',
    projectId: 'expense--tracker-6487e',
    storageBucket: 'expense--tracker-6487e.appspot.com',
    iosBundleId: 'com.cipherschools.assignment.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNyqDzBy_M3kq5QsV_B6hUT5FVna4FkKw',
    appId: '1:1094812966602:ios:91c3d709a07983a8245e33',
    messagingSenderId: '1094812966602',
    projectId: 'expense--tracker-6487e',
    storageBucket: 'expense--tracker-6487e.appspot.com',
    iosBundleId: 'com.cipherschools.assignment.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc4fvT5vskQMeOZ31Fw55_6AmesX8cVzo',
    appId: '1:1094812966602:web:9ba50ffe71d1d9b7245e33',
    messagingSenderId: '1094812966602',
    projectId: 'expense--tracker-6487e',
    authDomain: 'expense--tracker-6487e.firebaseapp.com',
    storageBucket: 'expense--tracker-6487e.appspot.com',
    measurementId: 'G-4BDDKTH8SS',
  );
}
